/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NovelIdRouteImport } from './routes/novel.$id'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as NovelIdIndexRouteImport } from './routes/novel.$id.index'
import { Route as AuthenticatedWriteIndexRouteImport } from './routes/_authenticated/write.index'
import { Route as AuthenticatedWriteNovelIdRouteImport } from './routes/_authenticated/write.$novelId'
import { Route as AuthenticatedWriteNovelIdIndexRouteImport } from './routes/_authenticated/write.$novelId.index'
import { Route as NovelIdChapterNumRouteImport } from './routes/novel.$id.chapter.$num'
import { Route as AuthenticatedWriteNovelIdChapterNewRouteImport } from './routes/_authenticated/write.$novelId.chapter.new'
import { Route as AuthenticatedWriteNovelIdChapterChapterIdRouteImport } from './routes/_authenticated/write.$novelId.chapter.$chapterId'

const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelIdRoute = NovelIdRouteImport.update({
  id: '/novel/$id',
  path: '/novel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const NovelIdIndexRoute = NovelIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NovelIdRoute,
} as any)
const AuthenticatedWriteIndexRoute = AuthenticatedWriteIndexRouteImport.update({
  id: '/write/',
  path: '/write/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWriteNovelIdRoute =
  AuthenticatedWriteNovelIdRouteImport.update({
    id: '/write/$novelId',
    path: '/write/$novelId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWriteNovelIdIndexRoute =
  AuthenticatedWriteNovelIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWriteNovelIdRoute,
  } as any)
const NovelIdChapterNumRoute = NovelIdChapterNumRouteImport.update({
  id: '/chapter/$num',
  path: '/chapter/$num',
  getParentRoute: () => NovelIdRoute,
} as any)
const AuthenticatedWriteNovelIdChapterNewRoute =
  AuthenticatedWriteNovelIdChapterNewRouteImport.update({
    id: '/chapter/new',
    path: '/chapter/new',
    getParentRoute: () => AuthenticatedWriteNovelIdRoute,
  } as any)
const AuthenticatedWriteNovelIdChapterChapterIdRoute =
  AuthenticatedWriteNovelIdChapterChapterIdRouteImport.update({
    id: '/chapter/$chapterId',
    path: '/chapter/$chapterId',
    getParentRoute: () => AuthenticatedWriteNovelIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/novel/$id': typeof NovelIdRouteWithChildren
  '/write/$novelId': typeof AuthenticatedWriteNovelIdRouteWithChildren
  '/write/': typeof AuthenticatedWriteIndexRoute
  '/novel/$id/': typeof NovelIdIndexRoute
  '/novel/$id/chapter/$num': typeof NovelIdChapterNumRoute
  '/write/$novelId/': typeof AuthenticatedWriteNovelIdIndexRoute
  '/write/$novelId/chapter/$chapterId': typeof AuthenticatedWriteNovelIdChapterChapterIdRoute
  '/write/$novelId/chapter/new': typeof AuthenticatedWriteNovelIdChapterNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/write': typeof AuthenticatedWriteIndexRoute
  '/novel/$id': typeof NovelIdIndexRoute
  '/novel/$id/chapter/$num': typeof NovelIdChapterNumRoute
  '/write/$novelId': typeof AuthenticatedWriteNovelIdIndexRoute
  '/write/$novelId/chapter/$chapterId': typeof AuthenticatedWriteNovelIdChapterChapterIdRoute
  '/write/$novelId/chapter/new': typeof AuthenticatedWriteNovelIdChapterNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/novel/$id': typeof NovelIdRouteWithChildren
  '/_authenticated/write/$novelId': typeof AuthenticatedWriteNovelIdRouteWithChildren
  '/_authenticated/write/': typeof AuthenticatedWriteIndexRoute
  '/novel/$id/': typeof NovelIdIndexRoute
  '/novel/$id/chapter/$num': typeof NovelIdChapterNumRoute
  '/_authenticated/write/$novelId/': typeof AuthenticatedWriteNovelIdIndexRoute
  '/_authenticated/write/$novelId/chapter/$chapterId': typeof AuthenticatedWriteNovelIdChapterChapterIdRoute
  '/_authenticated/write/$novelId/chapter/new': typeof AuthenticatedWriteNovelIdChapterNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/library'
    | '/novel/$id'
    | '/write/$novelId'
    | '/write/'
    | '/novel/$id/'
    | '/novel/$id/chapter/$num'
    | '/write/$novelId/'
    | '/write/$novelId/chapter/$chapterId'
    | '/write/$novelId/chapter/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/library'
    | '/write'
    | '/novel/$id'
    | '/novel/$id/chapter/$num'
    | '/write/$novelId'
    | '/write/$novelId/chapter/$chapterId'
    | '/write/$novelId/chapter/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/_authenticated/library'
    | '/novel/$id'
    | '/_authenticated/write/$novelId'
    | '/_authenticated/write/'
    | '/novel/$id/'
    | '/novel/$id/chapter/$num'
    | '/_authenticated/write/$novelId/'
    | '/_authenticated/write/$novelId/chapter/$chapterId'
    | '/_authenticated/write/$novelId/chapter/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  NovelIdRoute: typeof NovelIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novel/$id': {
      id: '/novel/$id'
      path: '/novel/$id'
      fullPath: '/novel/$id'
      preLoaderRoute: typeof NovelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/novel/$id/': {
      id: '/novel/$id/'
      path: '/'
      fullPath: '/novel/$id/'
      preLoaderRoute: typeof NovelIdIndexRouteImport
      parentRoute: typeof NovelIdRoute
    }
    '/_authenticated/write/': {
      id: '/_authenticated/write/'
      path: '/write'
      fullPath: '/write/'
      preLoaderRoute: typeof AuthenticatedWriteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/write/$novelId': {
      id: '/_authenticated/write/$novelId'
      path: '/write/$novelId'
      fullPath: '/write/$novelId'
      preLoaderRoute: typeof AuthenticatedWriteNovelIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/write/$novelId/': {
      id: '/_authenticated/write/$novelId/'
      path: '/'
      fullPath: '/write/$novelId/'
      preLoaderRoute: typeof AuthenticatedWriteNovelIdIndexRouteImport
      parentRoute: typeof AuthenticatedWriteNovelIdRoute
    }
    '/novel/$id/chapter/$num': {
      id: '/novel/$id/chapter/$num'
      path: '/chapter/$num'
      fullPath: '/novel/$id/chapter/$num'
      preLoaderRoute: typeof NovelIdChapterNumRouteImport
      parentRoute: typeof NovelIdRoute
    }
    '/_authenticated/write/$novelId/chapter/new': {
      id: '/_authenticated/write/$novelId/chapter/new'
      path: '/chapter/new'
      fullPath: '/write/$novelId/chapter/new'
      preLoaderRoute: typeof AuthenticatedWriteNovelIdChapterNewRouteImport
      parentRoute: typeof AuthenticatedWriteNovelIdRoute
    }
    '/_authenticated/write/$novelId/chapter/$chapterId': {
      id: '/_authenticated/write/$novelId/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/write/$novelId/chapter/$chapterId'
      preLoaderRoute: typeof AuthenticatedWriteNovelIdChapterChapterIdRouteImport
      parentRoute: typeof AuthenticatedWriteNovelIdRoute
    }
  }
}

interface AuthenticatedWriteNovelIdRouteChildren {
  AuthenticatedWriteNovelIdIndexRoute: typeof AuthenticatedWriteNovelIdIndexRoute
  AuthenticatedWriteNovelIdChapterChapterIdRoute: typeof AuthenticatedWriteNovelIdChapterChapterIdRoute
  AuthenticatedWriteNovelIdChapterNewRoute: typeof AuthenticatedWriteNovelIdChapterNewRoute
}

const AuthenticatedWriteNovelIdRouteChildren: AuthenticatedWriteNovelIdRouteChildren =
  {
    AuthenticatedWriteNovelIdIndexRoute: AuthenticatedWriteNovelIdIndexRoute,
    AuthenticatedWriteNovelIdChapterChapterIdRoute:
      AuthenticatedWriteNovelIdChapterChapterIdRoute,
    AuthenticatedWriteNovelIdChapterNewRoute:
      AuthenticatedWriteNovelIdChapterNewRoute,
  }

const AuthenticatedWriteNovelIdRouteWithChildren =
  AuthenticatedWriteNovelIdRoute._addFileChildren(
    AuthenticatedWriteNovelIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedWriteNovelIdRoute: typeof AuthenticatedWriteNovelIdRouteWithChildren
  AuthenticatedWriteIndexRoute: typeof AuthenticatedWriteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedWriteNovelIdRoute: AuthenticatedWriteNovelIdRouteWithChildren,
  AuthenticatedWriteIndexRoute: AuthenticatedWriteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface NovelIdRouteChildren {
  NovelIdIndexRoute: typeof NovelIdIndexRoute
  NovelIdChapterNumRoute: typeof NovelIdChapterNumRoute
}

const NovelIdRouteChildren: NovelIdRouteChildren = {
  NovelIdIndexRoute: NovelIdIndexRoute,
  NovelIdChapterNumRoute: NovelIdChapterNumRoute,
}

const NovelIdRouteWithChildren =
  NovelIdRoute._addFileChildren(NovelIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  NovelIdRoute: NovelIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
